version: "2.1"
services:

  postgresdb:
    image: postgres:15.2-alpine
    ports:
      - "5435:5435"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - back
    command: -p 5435
    volumes:
      - app-volume:/var/lib/postgresql/data

  pgadmin:
    image: "dpage/pgadmin4:6.20"
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
      - back

networks:
  back:
    driver: bridge
    
volumes:
  app-volume: #
